---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-360-slave
  labels:
    app: back-360-slave
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: back-360-slave
  template:
    metadata:
      labels:
        app: back-360-slave
    spec:
      containers:
      - name: back-360
        image: jaguaracr.azurecr.io/app/slave:latest
        imagePullPolicy: Always
        env:
        - name: DB_PORT
          value: "5864"
        - name: DB_HOST
          value: "10.243.0.5"
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: DB_ROLE
          value: "/slave"
        resources:
          requests:
            cpu: "8000m"
            memory: "40Gi" 
        ports:
        - containerPort: 8443