---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-360
  labels:
    app: app-360
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-360
  template:
    metadata:
      labels:
        app: app-360
    spec:
      containers:
      - name: app-360
        image: jaguaracr.azurecr.io/app/app-360:latest
        env:
        - name: CLIENT_HOST_URL
          value: "http://4.247.179.82"
        - name: MASTER_URL
          value: "http://4.247.179.82/master"
        - name: SLAVE_URL
          value: "http://4.247.179.82/slave"
        resources:
          requests:
            cpu: "1000m"
            memory: "4Gi" 
        ports:
        - containerPort: 80