---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-360-master
  labels:
    app: back-360-master
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0  
  selector:
    matchLabels:
      app: back-360-master
  template:
    metadata:
      labels:
        app: back-360-master
    spec:
      containers:
      - name: back-360
        image: jaguaracr.azurecr.io/app/master:latest
        imagePullPolicy: Always
        env:
        - name: DB_PORT
          value: "5864"
        - name: DB_HOST
          value: "10.243.0.4"
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: DB_ROLE
          value: "/master"          
        resources:
          requests:
            cpu: "4000m"
            memory: "20Gi" 
        ports:
        - containerPort: 8443